### ISSUE TITLE
file-loader issue

### ISSUE THREAD

**Issue by forehalo** [JeffreyWay/laravel-mix#112]
I just clone the example project and run. Seems there is a bug:

All fonts were built into `public/fonts` folder, and used in `public/css/app.css` file like:
```css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url(.//fonts/glyphicons-halflings-regular.eot?f4769f9bdb7466be65088239c12046d1);
  src: url(.//fonts/glyphicons-halflings-regular.eot?f4769f9bdb7466be65088239c12046d1)....
}
```
So when I visit it in browser(Chrome 55), the font files were requested like:
```
http://localhost:9090/css//fonts/glyphicons-halflings-regular.woff2?448c34a56d699c29117adc64c43affeb
```
each request url prefixes with `/css` which will cause them 404.

![image](https://cloud.githubusercontent.com/assets/8281226/22022393/ceadab16-dcfc-11e6-84e0-a176908ae0a4.png)
