### ISSUE TITLE
Define fonts destination

### ISSUE THREAD

**Issue by P9Q** [JeffreyWay/laravel-mix#1139]
Hi, Laravel-Mix copies my fonts from:

`assets/fonts/sansfont/sans.woff2`   to  `public/fonts/sans.woff2`,

Igonres **sansfont** folder,I want copy to `public/fonts/sansfont/sans.woff2`

is there any way to define that? 

Thank you

```scss
//fonts.scss

 @font-face {
    font-family: mySans;
    src:url('../fonts/sansfont/sans.woff2') format('woff2');
    font-style: normal;
    font-weight: 300;
  }
  .my-sans {
    font-family: mySans, Arial, Helvetica, sans-serif;
  }
```

```javascript
//webpack.mix.js

let mix = require('laravel-mix');

mix.js('resources/assets/js/app.js', 'public/js')
  .sass('resources/assets/sass/app.scss', 'public/css')
  .browserSync({
    proxy: 'localhost:8000'
  });
```
