### ISSUE TITLE
Prefix processCssUrls'ed by domain

### ISSUE THREAD

**Issue by ebess** [JeffreyWay/laravel-mix#1258]
Is there a way to prefix all processCssUrls'ed urls by a certain domain? If I'm developing and using hot reload, there no images. These are present after running the production build.

From
```css
.foo {
    background-image: url('../images/logo.png');
}
```

To
```css
.foo {
    background-image: url('http://app.hot:8080/images/logo.png');
}
```
