### ISSUE TITLE
PostCSS plugin not autoprefixing correctly

### ISSUE THREAD

**Issue by stephan-v** [JeffreyWay/laravel-mix#1284]
- Laravel Mix Version: 1.5.0 (`npm list --depth=0`)
- Node Version (`node -v`): 8.4.0
- NPM Version (`npm -v`): 5.3.0
- OS: Ubuntu 16.04

### Description:

The autoprefixer plugin provides a perfect example on how an attribute like `display: flex` is compiled:

https://github.com/postcss/autoprefixer#flexbox-filters-etc

```CSS
a {
    display: flex;
}
```

compiles to:

```CSS
a {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex
}
```

Except currently with Laravel Mix it omits the `display: -webkit-flex` leaving me with:

```CSS
a {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
}
```

Since Safari on iPhone 4(and other popular older browsers) needs this, it is pretty important this will get compiled as well. Is there any thing that can be changed about this?

### Steps To Reproduce:

Simply compile some CSS with and check the compiled output:

```CSS
a {
    display: flex;
}
```
