### ISSUE TITLE
Production build converts rgba colors to hsla

### ISSUE THREAD

**Issue by spaceemotion** [JeffreyWay/laravel-mix#1482]
- Laravel Mix Version: 2.0.0
- Node Version: 5.5.1
- NPM Version: 8.9.3
- OS: Mac Sierra

### Description:
I'm currently having trouble with mix changing my colors from rgba to hsla when running a production build. Is this something with PostCSS or libsass? Is there something I can disable?

**Reason why I don't want to use hsla just yet:** Even though the colors should work on the latest safari (iOS and OSX) they only appear correctly after an update with the color picker. If not, their transparency is not getting applied at all.

Here's the relevant css in all its variations:

Source:
```scss
.btn-default {
    background: linear-gradient(0deg, #f5f5f5, #ffffff);
    box-shadow: 0 1px 2px 0 rgba(black, 0.06), inset 1px 1px 0 0 rgba(white,.2);
    text-shadow: 0 1px rgba(white,.5);
}
```

Development:
```css
.btn-default {
    background: -webkit-gradient(linear, left bottom, left top, from(#f5f5f5), to(#ffffff));
    background: linear-gradient(0deg, #f5f5f5, #ffffff);
    -webkit-box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.06), inset 1px 1px 0 0 rgba(255, 255, 255, 0.2);
    box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.06), inset 1px 1px 0 0 rgba(255, 255, 255, 0.2);
    text-shadow: 0 1px rgba(255, 255, 255, 0.5);
}
```

Production (copied from devtools):
```css
.btn-default {
    background: -webkit-gradient(linear,left bottom,left top,from(#f5f5f5),to(#fff));
    background: linear-gradient(0deg,#f5f5f5,#fff);
    -webkit-box-shadow: 0 1px 2px 0 rgba(0,0,0,.06), inset 1px 1px 0 0 hsla(0,0%,100%,.2);
    box-shadow: 0 1px 2px 0 rgba(0,0,0,.06), inset 1px 1px 0 0 hsla(0,0%,100%,.2);
    text-shadow: 0 1px hsla(0,0%,100%,.5);
}
```

Here's a screenshot from Safari regarding a different class with the same problem: 

![image](https://user-images.githubusercontent.com/429147/36357551-fa667bde-14ff-11e8-930c-119d4ae6b260.png)
