### ISSUE TITLE
Svg not copied with folder

### ISSUE THREAD

**Issue by iAxel** [JeffreyWay/laravel-mix#1702]
- Laravel Mix Version: 2.1.11
- Node Version: 8.11.3
- NPM Version: 5.6.0
- OS: Win10

### Description:
I'm newbie, sorry if I wrote the resolved issue, my svg files are located in `resources/assets/images/svg/*`
After compiled, svg files are copied to `public/images/*`
I want it to be so `public/images/svg/*`

Please help me...

### Steps To Reproduce:
`webpack.mix.js`
```Javascript
let mix = require('laravel-mix');

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');

if (mix.inProduction()) {
    mix.version();
}
```

`resources/assets/sass/app.scss`
```Css
// Custom
@import 'bootstrap/custom'; //svg
```

`resources/assets/sass/bootstrap/_custom.scss`
```Css
// Custom
#app.admin {
  .navbar-logo {
    background: url('../images/svg/admin.svg') no-repeat;
  }
}

#app.default {
  .navbar-logo {
    background: url('../images/svg/default.svg') no-repeat;
  }
}
```
**After compiled:**
```Css
#app.admin .navbar-logo {
  background: url(/images/admin.svg?[hash]) no-repeat;
}

#app.default .navbar-logo {
  background: url(/images/default.svg?[hash]) no-repeat;
}
```
**But I want:**
```Css
#app.admin .navbar-logo {
  background: url(/images/svg/admin.svg?[hash]) no-repeat;
}

#app.default .navbar-logo {
  background: url(/images/svg/default.svg?[hash]) no-repeat;
}
```
Sorry for my Bad english...
