### ISSUE TITLE
Production mode removes quotes arround font-family

### ISSUE THREAD

**Issue by azeos** [JeffreyWay/laravel-mix#1794]
- Laravel Mix Version: 2.1.14
- Node Version:  10.9.0
- NPM Version: 6.2.0
- OS: Windows 10 Enterprise 64 bits

### Description:
When I run `npm run production` the quotation marks surrounding the `font-family` disappear. I know that's a valid syntax, but Firefox 62.0.3 doesn't render the font, in Chrome works just fine.

Is there any way to prevent that behavior?

I found that there is an option for `cssnano` to prevent this: `minifyFontValues: { removeQuotes: false }`. But I don't know how to pass it, nor if that plugin is being used.

### Steps To Reproduce:

**test.scss:**
```css
.test {
  font-family: 'Font Awesome 5 Free';
}
```

**webpack.mix.js:**
```js
let mix = require('laravel-mix');

mix.sass('resources/assets/sass/test.scss', 'public/css');
```

**test.css minified:**
```css
.test{font-family:Font Awesome\ 5 Free}
```

Thanks!
