### ISSUE TITLE
v4 updates prevent autoprefixer writing -webkit-box-sizing

### ISSUE THREAD

**Issue by cameronmurphy** [JeffreyWay/laravel-mix#1909]
I am testing against vanilla Laravel 5.7.19, Node 10.15.0, NPM 6.5.0, OS: CentOS 7

Laravel Mix v3.0.0 with default config:

```scss
* {
  box-sizing: border-box;
}
```
becomes:
```scss
* {
  -webkit-box-sizing: border-box;
          box-sizing: border-box;
}
```

Laravel Mix v4.0.12 with my config, attempting to select every single browser:
```js
mix.sass('resources/sass/app.scss', 'public/css')
   .options({
     postCss: [
       require('autoprefixer')({
         browsers: ['>= 0%'],
       })
     ]
   });
```
result:
```scss
* {
  box-sizing: border-box;
}
```

In fact, when experimenting with https://autoprefixer.github.io (matching version of Postcss and autoprefixer), the `-webkit-box-sizing` statement only disappears for `last 1 version`. It is added when `last 2 version` (or greater) is applied. Substituting `last 2 version` into the above config also yields the incorrect result.

I need assistance configuring Laravel Mix 4.* to add the `-webkit-box-sizing` statement.
