### ISSUE TITLE
How to pass env variable to scss file?

### ISSUE THREAD

**Issue by MovingGifts** [JeffreyWay/laravel-mix#2098]
In `webpack.mix.js` I can access an env variable with`process.env.MIX_URL`, but how can I pass that variable to use is an scss file compiled via:

```
mix.sass('site.scss', 'public/css')
```
So we can call it like this:
```scss
@font-face {
  font-family: 'My-Font';
  src: url('http://www.site.com/fonts/My-Font.ttf'); // orig working
  src: url(process.env.MIX_URL+'/fonts/My-Font.ttf'); // var not working
}
```
Any idea how to make it work?
