### ISSUE TITLE
pseudo selector before afer content  url changing 

### ISSUE THREAD

**Issue by polodev** [JeffreyWay/laravel-mix#2242]
```css
span {
	position: relative;
	&:after {
		content: url(../img/testimonial/quote2.png);
		bottom: -10px;
		right: -25px;
		position: absolute;
		filter: grayscale(100%);
	}
}
```

here content url become 
```css
url(./img/testimonial/quote2.png);

it supposed to be url(../*);
```
I mean start with single dot. incase of `background-image` its fine. it supposed to be double dot
My webpackConfig is following 

```
mix.less('./src/less/style.less', './assets/css/')
.options({
	processCssUrls: false,
}).
```
