### ISSUE TITLE
Sass production script compilation error

### ISSUE THREAD

**Issue by yepzy** [JeffreyWay/laravel-mix#2323]
-   Laravel Mix Version: 5.0.1
-   Node Version : 12.14.1 
-   NPM Version : 6.13.4
-   OS: Linux 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020

### Description:

I've maked a loop to generate few css selector rules with an increment, and as dev environnement, the CSS compiled is OK with all selectors wanted. 

Then when I execute the compilation as prod environnment, all selector are merge in one with a wrong value in the css rule.

### Steps To Reproduce:

- In a SCSS file write :

```scss
$i: 0;
@while $i <= 100 {
    .opacity-#{$i} {
        opacity: #{$i}+unquote('%') !important;
    }
    $i: $i + 10;
}
```

- Compilate with the script **development**

this give you:

```css
.opacity-0 {
  opacity: 0% !important;
}

.opacity-10 {
  opacity: 10% !important;
}

.opacity-20 {
  opacity: 20% !important;
}

.opacity-30 {
  opacity: 30% !important;
}

.opacity-40 {
  opacity: 40% !important;
}

.opacity-50 {
  opacity: 50% !important;
}

.opacity-60 {
  opacity: 60% !important;
}

.opacity-70 {
  opacity: 70% !important;
}

.opacity-80 {
  opacity: 80% !important;
}

.opacity-90 {
  opacity: 90% !important;
}

.opacity-100 {
  opacity: 100% !important;
}
```

- Compilate with the script **production**

this give you:

```css
.opacity-0{opacity:0!important}.opacity-10,.opacity-20,.opacity-30,.opacity-40,.opacity-50,.opacity-60,.opacity-70,.opacity-80,.opacity-90,.opacity-100{opacity:1%!important}
```
