### ISSUE TITLE
each .sass() call results in an additional Autoprefixer invocation resulting in runaway CPU and RAM usage

### ISSUE THREAD

**Issue by chamby** [JeffreyWay/laravel-mix#2426]
-   Laravel Mix Version: 5.0.4
-   Node Version: 12.18.1
-   NPM Version: 6.14.5
-   OS: MacOS 10.15.5 and Ubuntu 20.04

# Description:

Originally reported here: https://github.com/postcss/autoprefixer/issues/1323

There seems to be a recursion problem with something in my toolchain (`Laravel Mix -> Webpack -> Postcss -> Autoprefixer`) combined with a selector that has two prefix-able entries:

```css
:placeholder-shown::placeholder
```

You can see the output inflate as I add more SCSS files to my project.

Eventually this results in unmanageable CPU and RAM resource usage during compilation.

# Hypothesis:

My guess is that Postcss and/or Autoprefixer is being invoked on the same output multiple times. Autoprefixer is not idempotent and it begins to geometrically increase output.

# Steps To Reproduce:

## Autoprefixer Disabled

test.scss INPUT:
```scss
input {
  &:placeholder-shown::placeholder {
      opacity: 0;
  }
}
```

webpack.mix.js
```JS
let mix = require('laravel-mix');

mix.options({
  autoprefixer: {
    enabled: false
  }
});

mix.sass('resources/assets/scss/test.scss', 'public/css');
```

test.css OUTPUT
```css
input:placeholder-shown::placeholder {
  opacity: 0;
}
```

---

## Autoprefixer Enabled with One Input File

test.scss INPUT:
```scss
input {
  &:placeholder-shown::placeholder {
      opacity: 0;
  }
}
```

webpack.mix.js
```JS
let mix = require('laravel-mix');

mix.options({
  autoprefixer: {
    enabled: true
  }
});

mix.sass('resources/assets/scss/test.scss', 'public/css');
```

test.css OUTPUT
```css
input:placeholder-shown::-moz-placeholder {
  opacity: 0;
}
input:placeholder-shown:-ms-input-placeholder {
  opacity: 0;
}
input:placeholder-shown::-ms-input-placeholder {
  opacity: 0;
}
input:-moz-placeholder-shown::placeholder {
  opacity: 0;
}
input:-ms-input-placeholder::placeholder {
  opacity: 0;
}
input:placeholder-shown::placeholder {
  opacity: 0;
}
```

---

### Autoprefixer Enabled with Two Input Files

test.scss INPUT:
```scss
input {
  &:placeholder-shown::placeholder {
      opacity: 0;
  }
}
```

test-01.scss INPUT:
```scss
```

webpack.mix.js
```JS
let mix = require('laravel-mix');

mix.options({
  autoprefixer: {
    enabled: false
  }
});

mix.sass('resources/assets/scss/test.scss', 'public/css');
mix.sass('resources/assets/scss/test-01.scss', 'public/css');
```

test.css OUTPUT
```css
input:-moz-placeholder-shown::-moz-placeholder {
  opacity: 0;
}
input:placeholder-shown::-moz-placeholder {
  opacity: 0;
}
input:-ms-input-placeholder:-ms-input-placeholder {
  opacity: 0;
}
input:placeholder-shown:-ms-input-placeholder {
  opacity: 0;
}
input:-ms-input-placeholder::-ms-input-placeholder {
  opacity: 0;
}
input:placeholder-shown::-ms-input-placeholder {
  opacity: 0;
}
input:placeholder-shown:-ms-input-placeholder {
  opacity: 0;
}
input:-ms-input-placeholder::placeholder {
  opacity: 0;
}
input:placeholder-shown::-moz-placeholder {
  opacity: 0;
}
input:placeholder-shown:-ms-input-placeholder {
  opacity: 0;
}
input:placeholder-shown::-ms-input-placeholder {
  opacity: 0;
}
input:-moz-placeholder-shown::placeholder {
  opacity: 0;
}
input:-ms-input-placeholder::placeholder {
  opacity: 0;
}
input:placeholder-shown::placeholder {
  opacity: 0;
}
```

test-01.css OUTPUT
```css
```
