### ISSUE TITLE
Loading worker causes "SecurityError: Content on http://127.0.0.1:8000/ is not allowed data from http://localhost:8080/ExampleWorker.worker.js"

### ISSUE THREAD

**Issue by caugner** [JeffreyWay/laravel-mix#2619]
-   Laravel Mix Version: 5.0.7
-   Node Version (`node -v`): 12.18.3
-   NPM Version (`npm -v`): 6.14.8
-   OS: Windows 10

### Description:

In my Laravel/Vue project, I'm using a worker (`ExampleWorker`) that I import using [worker-loader](https://github.com/webpack-contrib/worker-loader) as follows:

```
import ExampleWorkerfrom "worker-loader!./ExampleWorker.js";
```

It works in the `prod` build, but in the `hot` build, loading the worker fails, causing an error in the browser console:

```
Sicherheitsfehler: Inhalt auf http://127.0.0.1:8000/ darf keine Daten von http://localhost:8080/ExampleWorker.worker.js laden.
SecurityError: Content on http://127.0.0.1:8000/ is not allowed to load data from http://localhost:8080/ExampleWorker.worker.js
```

Any ideas how to circumvent this?

### Steps To Reproduce:

1. Install `worker-loader`.
2. Create any Worker.
3. Import worker using `worker-loader`.
4. Run `php artisan serve` and `npm run hot`.
5. Access page that uses the JS that imports the worker.

**Comment by caugner** [comment]
Unfortunately, I still haven't found a solution or workaround.

**Comment by caugner** [comment]
The fact that `localhost:8080` is hard-coded in [`Illuminate\Foundation\Mix`](https://github.com/laravel/framework/blob/275c78c97e007e4a9d771d4d1caa1c77ebfdcf94/src/Illuminate/Foundation/Mix.php#L39) doesn't make it easy to find a workaround.

**Comment by caugner** [comment]
I found the ugly workaround of using a Docker Compose config with (a) an `app` container (`php:fpm`) serving the app, (b) a `hot` container (`node`) running the `webpack-dev-server` and (c) a `nginx` container on port 8080 proxying to both containers:

`./docker-compose.yml`:
```yml
services:
  app:
    php:fpm
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: sh -c 'composer install && php-fpm'

  hot:
    image: node
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: sh -c 'yarn install && yarn run hot --host 0.0.0.0'
    healthcheck:
      test: curl -f http://localhost:8080/webpack-dev-server || exit 1

nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker-compose/nginx:/etc/nginx/conf.d/
```

`./docker-compose/nginx/app.conf`:
```
server {
    listen 80;
    index index.php index.html;
    root /var/www/html/public;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ (^/js/|^/sockjs-node|\.hot-update.json$) {
        proxy_pass          http://hot:8080;
        proxy_http_version  1.1;
        proxy_set_header    Upgrade $http_upgrade;
        proxy_set_header    Connection "upgrade";
        proxy_set_header    Host $http_host;
        proxy_set_header    X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }
}
```
