### ISSUE TITLE
processCssUrls broken with PostCSS

### ISSUE THREAD

**Issue by tillkruss** [JeffreyWay/laravel-mix#2654]
-   Laravel Mix Version: 6.0.0-beta.15
-   Node Version: v15.0.1
-   NPM Version: 7.0.3
-   OS: macOS 11.0.1

### Description:

As of beta 15 setting `processCssUrls` to `false` is still copying the files and URLs have have cache busters.

The font files are copied from `public/assets/fonts` to `public/fonts`.

### Steps To Reproduce:

```js
mix
    .options({
        processCssUrls: false,
    })
    .postCss('resources/css/app.css', 'public/assets/css', [
        require('postcss-import'),
        require('tailwindcss'),
        require('postcss-nested'),
        require('autoprefixer'),
    ]);
```

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
    @font-face {
        font-family: 'Inter';
        font-style: normal;
        font-weight: 100;
        font-display: swap;
        src: url('/public/assets/fonts/inter-thin.woff2') format('woff2');
    }
}
```
