### ISSUE TITLE
Wrong CSS Order after build

### ISSUE THREAD

**Issue by nmfzone** [JeffreyWay/laravel-mix#2793]
-   Laravel Mix Version: 6.0.6
-   Node Version (`node -v`): 12.16.1
-   NPM Version (`npm -v`): 6.13.4
-   OS: OSX

### Description:
The css order after build (`public/css/app.css`) is different from the source order (`resources/sass/app.scss`). It's happening when import `.css` in `.scss` file.
The `.css` file always "prepended" to the output, so it didn't respect the order.

For example:

*resources/css/other.css*
```css
.middle {
    margin-left: 0;
}
```

*resources/sass/app.scss*
```scss
.top {
    margin-top: 0;
}

@import "../css/other.css";

.bottom {
    margin-bottom: 0;
}
```

The output should be (AFAIK):
```css
.top {
    margin-top: 0;
}

.middle {
    margin-left: 0;
}

.bottom {
    margin-bottom: 0;
}
```

But, it doesn't. The output is
```css
.middle {
    margin-left: 0;
}

.top {
    margin-top: 0;
}

.bottom {
    margin-bottom: 0;
}
```

### Steps To Reproduce:
1. Create `.scss` file and `.css` file
2. Import `.css` file inside `.scss`
3. Build

Repro url: https://github.com/nmfzone/laravel-mix-repro/tree/tailwind
