### ISSUE TITLE
static site font-awesome and bootstrap-icons icons not displayed?

### ISSUE THREAD

**Issue by devhoussam** [JeffreyWay/laravel-mix#2974]
I have some issues when I use laravel-mix to compile scss files to CSS the font-awesome and bootstrap-icons and other libraries that contain web fonts not displayed even if it installed well??

**my projects file structure:**

```
my-app/
├── dist/
│   ├── assets/
│   │   ├── css/
│   │   │    ├── app.css
│   ├── fonts/
│   │   ├── vendor/
│   │   │    ├── @fortawesome/
│   │   │    ├── bootstrap-icons/
│   ├── images/
├── src/
│   ├── scss/
│   │   ├── app.scss
│── index.html
│── package.json
└── webpack.mix.js
```

**my src/scss/app.scss file:**

```
@import "~bootstrap-icons/font/bootstrap-icons";

$fa-font-path: "~@fortawesome/fontawesome-free/webfonts";

@import "~@fortawesome/fontawesome-free/scss/fontawesome";
@import "~@fortawesome/fontawesome-free/scss/solid";
@import "~@fortawesome/fontawesome-free/scss/brands";
@import "~@fortawesome/fontawesome-free/scss/regular";
```

**Dev Console Error msg :**

![Image](https://i.stack.imgur.com/3SrdA.png)

**Comment by mikesaintsg** [comment]
If you're just running the html file in the browser, then not all the files in the dist folder will be served, only those in the script and link tags will be picked up on. For local development, you should spin up an expressjs server to serve all the files, even just statically.

For example, I would put a file called `server.js` in the root folder with the following:
```js
const express = require('express')
const app = express()
const port = 3000

app.use('/', express.static('public'))

app.listen(port, () => {
    console.log(`Example app listening on http://localhost:${port}`)
})

```

Then update my `package.json` file, with the following scripts:

```json
  "scripts": {
    "serve": "node ./server.js",
    "dev": "npm run development && npm run serve",
```

Give that a shot, and let me know if it worked. It used to stump me too, when i would use mox outside of the Laravel context.

**Comment by toby5box** [comment]
I'm having the same problem, but only in a Docker build. The bootstrap-icons fonts are not copied. 

If I run `npx mix` locally, bootstrap-icons fonts are copied correctly.

### webpack.mix.js

```js
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
  .copyDirectory('resources/images', 'public/images');
```

### app.scss

```scss
@import "~bootstrap-icons/font/bootstrap-icons";

```

### bootstrap-icons

```scss
$bootstrap-icons-font: "bootstrap-icons" !default;
$bootstrap-icons-font-src: url("./fonts/bootstrap-icons.woff2?524846017b983fc8ded9325d94ed40f3") format("woff2"),
url("./fonts/bootstrap-icons.woff?524846017b983fc8ded9325d94ed40f3") format("woff") !default;

@font-face {
  font-family: $bootstrap-icons-font;
  src: $bootstrap-icons-font-src;
}

...
```

The docker build is running in `node:lts-alpine`

Locally I just have 
```
$ npm --version
8.5.5
$ node --version
v17.8.0

  "laravel-mix": "^6.0.43",
```
