### ISSUE TITLE
SCSS not properly rendering sass variables in css variable declarations.

### ISSUE THREAD

**Issue by Anticom** [JeffreyWay/laravel-mix#3024]
-   Laravel Mix Version: 6.0.25 (`npm list --depth=0`)
-   Node Version (`node -v`): v14.17.1
-   NPM Version (`npm -v`): 7.18.1
-   OS: Ubuntu 16.04.7 LTS

### Description:
It seems that when compiling scss using `mix.sass('in.scss', 'out')` that sass variables don't get expanded when placed in [css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties).

### Steps To Reproduce:

Input:
```scss
$clr: green;

:root {
  --my-var: $clr;
  color: $clr;
}
```

Expected output:
```css
:root {
  --my-var: green;
  color: green;
}
```

Actual output:
```css
:root {
  --my-var: $clr;
  color: green;
}
```

**Comment by Anticom** [comment]
Okay so this seems to be a limitation sass has. It can be circumvented by wrapping the variable name in `#{}`:

```scss
$clr: green;

:root {
  --my-var: #{$clr};
  color: $clr;
}
```

produces the desired output.
