### ISSUE TITLE
After update from 6.0.25 to 6.0.27 rule not used anymore

### ISSUE THREAD

**Issue by schonhoff** [JeffreyWay/laravel-mix#3053]
-   Laravel Mix Version: 6.0.25/6.0.27
-   Node Version (`node -v`): 14.17.3
-   NPM Version (`npm -v`): 6.14.14
-   OS: Windows 10

### Description:
After I updated my Laravel-mix to the new version my browser showed me this warning:
failed to decode downloaded font

No font was loaded correctly and I changed nothing else. With version 6.0.25 it worked. I have a special rule for my fonts:

```js
mix.webpackConfig({
	module: {
		rules: [{
			test: /(\.(woff2?|ttf|eot|otf)$|font.*\.svg$)/,
			loaders: [{
				loader: 'file-loader',
				options: {
					name: function() {
						return 'webfonts/[name].[ext]';
					},
				},
			}],
		}],
	},
});
```

This rule isn't working after the update. I saw it later in the log of my cmd. There was a font/ directory created in my public path and this fonts has a versioning again. That is why I wrote the rule above.

### Steps To Reproduce:
1.) local font in resource/assets/webfonts
2.) CSS/SCSS Code (fonttest.scss)
```css
    @font-face {
        font-family: 'humnst777_cn';
        src: url('../webfonts/MYFONT.woff2') format('woff2'),
        url('../webfonts/MYFONT.woff') format('woff');
        font-weight: normal;
        font-style: normal;
        font-display: swap
    }
[...more css code here...]
```
3.) Webpack.mix.js Code:
```js
let mix = require('laravel-mix');
mix.webpackConfig({
	// object will be merged with Laravel Mix config, so matching rules will be overwritten
	module: {
		rules: [{
			// overwriting file-loader rule for fonts in order to remove the hash (so we can pre-load without downloading it twice)
			test: /(\.(woff2?|ttf|eot|otf)$|font.*\.svg$)/,
			loaders: [{
				loader: 'file-loader',
				options: {
					name: function() {
						// if (!/node_modules|bower_components/.test(path)) {
							return 'webfonts/[name].[ext]';
						// }
						// const pathUpdated = path.replace(/\\/g, '/').replace(/((.*(node_modules|bower_components))|fonts|font|assets)\//g, '');
						// return `fonts/vendor/${pathUpdated}`;
					},
				},
			}],
		}],
	},
});
mix.sass('resources/assets/sass/fonttest.scss', 'public/css').version();
```
I really hope there is a workaround or a fix for this issue. Thanks for the awesome job :-)
