### ISSUE TITLE
resolve path relative to public folder

### ISSUE THREAD

**Issue by dev-seahouse** [JeffreyWay/laravel-mix#364]
I have mix copied semantic-sass assets from node_modules to public folder :
``` javascript
// /webpack.mix.js
mix.copy('node_modules/semantic-ui-sass/app/assets/images/', 'public/images/', false)
  .copy('node_modules/semantic-ui-sass/app/assets/fonts/', 'public/fonts/', false)
  .js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
```
This is how it looks like after copying:
**source :**
```
/node_modules
 |+semantic-ui-sass
     |+app
        |+assets
            |+fonts
               |+semantic-ui
                  |-icons.eof
                  |-icons.otf
                     ......
           |+stylesheets
               |+semantic-ui
                  |+elements
                      |_icon.scss 
                 .......
```
**dest:** 
```
/public
 |+css
     |-app.css
 |+fonts
     |-semantic-ui
     |-icons.eot
     |-icons.otf
     |-icons.svg
     |-icons.ttf
     |-icons.woff
     |-icons.woff2
```
Then imported icons inside /resource/assets/sass/app.scss
```scss
// resources/assets/sass/app.scss
@import 'node_modules/semantic-ui-sass/app/assets/stylesheets/semantic-ui/elements/icon';
```
After running **`npm run dev`**, this is the result produced :
**source:**
```scss
  src: font-url("semantic-ui/icons.eot");
  src: font-url("semantic-ui/icons.eot?#iefix") format('embedded-opentype')
    ...
```
**dest:**
``` css
/* public/css/app.css */
@font-face {
  src: font-url("./../../../node_modules/semantic-ui-sass/app/assets/fonts/semantic-ui/icons.eot");
  font-url("./../../../node_modules/semantic-ui-sass/app/assets/fonts/semantic-ui/icons.eot") format("embedded-opentype");
  .....
}
```
But this is want i want :
``` css
/* public/css/app.css */
@font-face {
  src: font-url("fonts/semantic-ui/icons.eot");
  src: font-url("fonts/semantic-ui/icons.eot");
  .....
}
```
I was wondering is there some way to configure mix to resolve urls inside scss relative to production public folder instead of dependencies source folder without changing the source?

**Comment by swt83** [comment]
I have this problem too.  I can't load FontAwesome via SCSS because webpack insists on absolute URLs instead of relative ones.

This works, but loads the URLs as a file looking at ``localhost/fonts`` instead of my public directory:

```
$fa-font-path: "/../fonts/";
@import "node_modules/font-awesome/scss/font-awesome";
```

This is what I need, but won't work because it's a relative directory:

```
$fa-font-path: "../fonts";
@import "node_modules/font-awesome/scss/font-awesome";
```

**Comment by swt83** [comment]
Aha!

Add this to your ``webpack.mix.js`` file:

```
.options({ processCssUrls: false })
```

As referenced [here](https://github.com/JeffreyWay/laravel-mix/issues/187).

**Comment by httpoz** [comment]
Dankie @swt83

**Comment by raniesantos** [comment]
Is this something webpack changed on their end recently?

One of my recent projects used laravel-mix 0.8.8 and I'm pretty sure I got bootstrap's glyphicons linked properly without extra configuration.

I'll be watching this issue.

**Comment by jhourlad** [comment]
How about relative asset path? e.g. ``../img/image.png``? 
Also doesn't properly resolve.

**Comment by leoquijano** [comment]
I'm having a similar issue.

I'm not sure ```processCssUrls``` will help people that have non-standard directory layouts (such as in a shared hosting), or hosted in subdirectoreis. 

Since fonts are already in the public/ directory, shouldn't paths be relative anyway?

**Comment by Mark-Hoog** [comment]
Here's what I did for relative asset paths: 

*webpack.mix.js*
```Javascript
mix.webpackConfig({
    resolve: {
        alias: {
            '@': path.resolve('src')
        }
    }
}).options({
    extractVueStyles: true
}).js('src/main.js', 'dist/').sass('src/assets/scss/app.scss', 'dist');
```

*fonts.scss*
```scss
@font-face {
  font-family: 'font';
  src: url('~@/assets/fonts/font-webfont.woff2') format('woff2'),
  url('~@/assets/fonts/font-webfont.woff') format('woff');
  font-weight: bold;
  font-style: normal;
}
```

*App.vue*
``` scss
  ....
<style lang="scss">

    @import 'assets/scss/module/fonts';
....
```

Offcourse these aren't node-modules but they are a use case that can be applied to this issue.
