### ISSUE TITLE
Missing support for .cur files

### ISSUE THREAD

**Issue by dannehl** [JeffreyWay/laravel-mix#420]
In a few less or sass packages we are using external cursor files (*.cur) which are currently breaking webpack compilation.

```css
.my-class {
  cursor: url('/custom_cursor.cur') 4 4, move; 
}
```

Maybe it would be useful to have these extension added by  default.

i.e.

```js
{
    test: /\.(cur|ani)$/,
    loader: 'file-loader',
    options: {
        name: 'cursors/[name].[ext]?[hash]',
        publicPath: '/'
    }
},
```
