### ISSUE TITLE
Does autoprefixer also apply for sass compile?

### ISSUE THREAD

**Issue by filipveschool** [JeffreyWay/laravel-mix#461]
Hi,

I wanted to ask if all css also will be prefixed by using autoprefixer where necessary when you compile your SCSS files with laravel mix?

I see it does happen when you use postcss, but does this also count for SCSS or what should we do herefore?

I hope my question is understandable? I know it's not really an issue, but didn't know where to put it?

**Comment by JeffreyWay** [comment]
Yes, it does. Give it a try. In `resources/assets/sass/app.scss`, add:

```css
.example {
    transition: all 1s;
}
```

That should compile down to:

```css
body {
  -webkit-transition: all 1s;
  transition: all 1s;
}
```
