### ISSUE TITLE
Custom setPublicPath and problem with url for awesome and glyphicon fonts

### ISSUE THREAD

**Issue by mirbatworks** [JeffreyWay/laravel-mix#490]
I'm using custom location for assets `public/themes/default/assets/`
Awesome Fonts are installed with `npm install font-awesome` and with mix.copy function awesome and glyphicons are copied in public/themes/default/assets/fonts folder
There is no error on `npm run dev` command and my backend.js and backend.css files are created. Problem is that in backend.css url's for fonts are not updated
This is from backend.css:
```css
@font-face {
  font-family: 'FontAwesome';
  src: url(/fonts/fontawesome-webfont.eot?674f50d287a8c48dc19ba404d20fe713);
  src: url(/fonts/fontawesome-webfont.eot?674f50d287a8c48dc19ba404d20fe713?#iefix&v=4.7.0) format("embedded-opentype"), url(/fonts/fontawesome-webfont.woff2?af7ae505a9eed503f8b8e6982036873e) format("woff2"), url(/fonts/fontawesome-webfont.woff?fee66e712a8a08eef5805a46892932ad) format("woff"), url(/fonts/fontawesome-webfont.ttf?b06871f281fee6b241d60582ae9369b9) format("truetype"), url(/fonts/fontawesome-webfont.svg?912ec66d7572ff821749319396470bde#fontawesomeregular) format("svg");
  font-weight: normal;
  font-style: normal;
}
```
URL should look like url(../fonts/) - to start with two dots. But, it's not. I need to manually edit this path every time.
My style is included properly in page because all other staff are visible.
How to properly set this in Laravel-mix?
This is my webpack.mix.js:
```javascript
const { mix } = require('laravel-mix');
....
mix.setPublicPath('public/themes/default/assets/');

var themePath = 'public/themes/default/assets/';

mix.js(themePath+'js/app.js', themePath+'js/backend.js')
   .sass(themePath+'sass/app.scss', themePath+'css/backend.css')
   .copy('node_modules/font-awesome/fonts', themePath+'fonts');
```
Note, there is no errors in `npm run dev`
