### ISSUE TITLE
mix.sass' pluginOptions is ignored

### ISSUE THREAD

**Issue by Sniper296** [JeffreyWay/laravel-mix#509]
- Laravel Mix Version: 0.8.8
- Node Version: 7.7.1
- NPM Version: 4.3.0
- OS: Arch Linux

### Description:
mix.sass' pluginOptions is ignored.

### Steps To Reproduce:
- `laravel new Test && cd Test`
- `npm install`
- edit webpack.mix.js to:
```javascript
const { mix } = require('laravel-mix');
mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css', { outputStyle: 'compact' });
```
- `npm run dev`

### Expected Results:
public/css/app.css (line 5-6):
```css
html { font-family: sans-serif; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; }

body { margin: 0; }
```

### Actual Results:
public/css/app.css (line 9-17):
```css
html {
  font-family: sans-serif;
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
}

body {
  margin: 0;
}
```

[Sample Repo](https://github.com/Sniper296/laravel-mix-test)
