### ISSUE TITLE
a bug,compile less background relative url will be absolute

### ISSUE THREAD

**Issue by lichnow** [JeffreyWay/laravel-mix#513]
webpack.config.js
```
mix
        .less(manager.source + '/styles/app.less', manager.compile + '/css')
        .options({
            processCssUrls: false
        });
```
app.less
```
@base-img-url: "../pages/img";
.set{
    background: url('@{base-img-url}/icons/top_tray_2x.png');
}
```
compiled app.css
```
.set {
    background: url('pages/img/icons/top_tray_2x.png');
  }
```

**Comment by JeffreyWay** [comment]
I just tried this out on my machine:

#### webpack.mix.js

```js
var mix = require('laravel-mix');

mix.less('resources/assets/less/app.less', 'css')
    .options({
        processCssUrls: false
    });
```

#### resources/assets/less/app.less

```css
@base-img-url: "../pages/img";

.set {
    background: url('@{base-img-url}/icons/top_tray_2x.png');
}
```

#### public/css/app.css

```css
.set {
  background: url('../pages/img/icons/top_tray_2x.png');
}
```

So it's working properly.
