### ISSUE TITLE
Preprend domain to CSS URLs

### ISSUE THREAD

**Issue by tillkruss** [JeffreyWay/laravel-mix#706]
Is there a way to add a configurable domain to URLs in Sass, so turning this:

```sass
.foo { background-image: url('/images/bar.png'); }
```
Into this:
```css
.foo { background-image: url('https://example.com/images/bar.png'); }
```
Not sure if this is the right place to ask questions like this.
