### ISSUE TITLE
"Duplicate" css definitions removed

### ISSUE THREAD

**Issue by whodidthis** [JeffreyWay/laravel-mix#818]
- Laravel Mix Version: #.#.# (`npm list --depth=0`)
0.11.4
- Node Version (`node -v`): 
v7.8.0
- NPM Version (`npm -v`): 
4.2.0
- OS:
windows 10 

### Description:
I'm having trouble understanding which part of the toolchain removes important "duplicate" css definitions from imported stylesheets when running `npm run production`. I'm trying to use a library called [material components for the web](https://github.com/material-components/material-components-web). 

With a clean new project having the following app.scss 
```scss
:root {
  --mycolor: #ccc;
}
body {
  background-color: #ccc;
  background-color: var(--mycolor, #ccc);
}
```
turns into a correct stylesheet
```css
:root{--mycolor:#ccc}body{background-color:#ccc;background-color:var(--mycolor,#ccc)}
```

However, if I import an scss file that uses duplicate css definitions the same way, e.g.
```scss
@import "@material/drawer/mdc-drawer";
```
when running `npm run dev` produces
```css
.mdc-persistent-drawer__drawer {
  background: #fff;
  background: var(--mdc-theme-background, #fff);
  -webkit-transform: translateX(-107%);
          transform: translateX(-107%);
  -webkit-transform: translateX(calc(-100% - 20px));
          transform: translateX(calc(-100% - 20px));
  /* ...etc */
}
```
but with `npm run prod` produces
```css
.mdc-persistent-drawer__drawer {
    background: var(--mdc-theme-background, #fff);
    -webkit-transform: translateX(calc(-100% - 20px));
    transform: translateX(calc(-100% - 20px));
    /* ...etc */
}
```

So important definitions are deleted and then things don't work anymore on IE11 etc.

### Steps To Reproduce:
```
laravel new testapp
cd testapp
npm install
npm install --dev material-components-web
```
add node_modules to `includePaths` in webpack.mix.js
```js
mix.sass('resources/assets/sass/app.scss', 'public/css', {
      includePaths: [
        "node_modules/",
      ],
    })
```
then try stylesheets above and try `npm run dev` and `npm run prod`.

Github repository [here](https://github.com/whodidthis/laravel-css-testing/commit/237a5221a1bc7d7443acd9a14861e81485a0f9ba)
